# Module: AlmacenesMapas
# Document : modules\AlmacenesMapas\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 17.12.2011 19:00:12
#
---
Colores:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Colores
  id_video: colores
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Colores
  table: colores
  primarykey: IDColor
  linkBy:
  records_per_page: 15
  order_by:
    -
      title: Color a-z
      criteria: Color ASC
    -
      title: Color z-a
      criteria: Color DESC
  search_default: Color
  referenced_entities:
  columns:
    -
      title: IDColor
      field: IDColor
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
    -
      title: Color
      field: Color
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: string
        length: 3
        min: null
        max: null
        message: Valor Requerido
    -
      title: Selector
      field: Selector
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: string
        length: 3
        min: null
        max: null
        message: Valor Requerido