# Module: Perfiles
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
Perfiles:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Perfiles de Usuario
  conection: empresas
  entity: Perfiles
  table: perfiles
  primarykey: IDPerfil
  records_per_page: 10
  order_by:
    -
      title: Perfil a-z
      criteria: Perfil ASC
    -
      title: Perfil z-a
      criteria: Perfil DESC
  search_default: Perfil
  columns:
    -
      title: IDPerfil
      field: IDPerfil
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    -
      title: Perfil
      field: Perfil
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: YES
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: Administrador
      field: Administrador
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: null
        length: null
        min: null
        max: null
        message: Valor Requerido
