# Module: TallasColores
# Document : modules\TallasColores\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 17.12.2011 19:00:12
#
---
TallasColores:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Tallas y Colores
  id_video: tallasColores
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity:
  table:
