# Module: AlmacenesMapas
# Document : modules\AlmacenesMapas\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 17.12.2011 19:00:12
#
---
AlmacenesMapas:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Tallas
  id_video: tallas
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Tallas
  table: tallas
  primarykey: IDTalla
  linkBy:
  records_per_page: 15
  order_by:
    -
      title: Talla a-z
      criteria: Talla ASC
    -
      title: Talla z-a
      criteria: Talla DESC
  search_default: IDUbicacion
  referenced_entities:
  columns:
    -
      title: IDTalla
      field: IDTalla
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
    -
      title: Talla
      field: Talla
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: string
        length: 3
        min: null
        max: null
        message: Valor Requerido

