# Module: TiposIva
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
TiposIva:
  login_required: YES
  permission_control: YES
  help_file: help.html.twig
  title: Tipos de Iva
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: TiposIva
  table: tipos_iva
  primarykey: IDIva
  records_per_page: 10
  order_by:
    -
      title: Tipo a-z
      criteria: Tipo ASC
    -
      title: Tipo z-a
      criteria: Tipo DESC
  search_default: Tipo
  columns:
    -
      title: Codigo
      field: IDIva
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    -
      title: Tipo
      field: Tipo
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: string
        length: 30
        min: null
        max: null
        message: Valor Requerido
    -
      title: Iva
      field: Iva
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: 0
        max: 99
        message: Valor Requerido (0-99)
    -
      title: Recargo
      field: Recargo
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: 0
        max: 20
        message: Valor Requerido (0-20)
    -
      title: Retencion
      field: Retencion
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: 0
        max: 99
        message: Valor Requerido (0-99)
